services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    volumes:
      - faq_elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  panel-rag:
    build:
      context: .
      dockerfile: Dockerfile
    image: panel-rag
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - OLLAMA_HOST=http://ollama:11434
    container_name: panel-rag
    ports: 
      - "5006:5006"


volumes:
  faq_elasticsearch_data:
    external: true
  ollama_data:
    external: true
